apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dockerconfig
  namespace: imagepullsecret-patcher-jfrog
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: global-jfrog
      secretKey: globaljfrog
  refreshInterval: 1m
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: sealed-regcred-jfrog
    template:
      data:
        .dockerconfigjson: .dockerconfigjson'
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
